# Generated by Django 4.2.14 on 2024-07-13 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstLink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_linked_dial', to='puzzlebox.dial')),
                ('secondLink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_linked_dial', to='puzzlebox.dial')),
            ],
        ),
    ]
