# Generated by Django 4.2.14 on 2024-07-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlebox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dial',
            name='dialCenter',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='dial',
            name='dialPosition',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dial',
            name='firstLinkDir',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dial',
            name='pistonPosition',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dial',
            name='secondLinkDir',
            field=models.IntegerField(default=1),
        ),
    ]
