# Generated by Django 4.2.14 on 2024-07-13 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlebox', '0002_dial_dialcenter_dial_dialposition_dial_firstlinkdir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dial',
            name='dialNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dial',
            name='firstLink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_linked_dial', to='puzzlebox.dial'),
        ),
        migrations.AlterField(
            model_name='dial',
            name='secondLink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_linked_dial', to='puzzlebox.dial'),
        ),
    ]
