# Generated by Django 4.2.14 on 2024-07-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlebox', '0003_dial_dialnumber_alter_dial_firstlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dial',
            name='dialLetter',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
